enum ROUTES {
  // Root Navigator start
  LANDING = 'LANDING',

  LOGIN = 'LOGIN',

  SIGNUP = 'SIGNUP',

  MANAGE_CONNECTED_CHAINS = 'MANAGE_CONNECTED_CHAINS',

  MANAGE_CONNECTED_APPS = 'MANAGE_CONNECTED_APPS',

  HOME_TABS = 'HOME_TABS',

  HOME_DISCOVER = 'HOME_DISCOVER',

  HOME_FOLLOWING = 'HOME_FOLLOWING',

  PASSWORD_MANIPULATION = 'PASSWORD_MANIPULATION',

  CONFIRM_MODAL = 'CONFIRM_MODAL',

  TEXTONLY_MODAL = 'TEXTONLY_MODAL',

  SETTINGS = 'SETTINGS',

  SETTINGS_PROFILES = 'SETTINGS_PROFILES',

  SETTINGS_COMMUNITY = 'SETTINGS_COMMUNITY',

  SETTINGS_REVEAL_SECRET_PHRASE = 'SETTINGS_REVEAL_SECRET_PHRASE',

  SETTINGS_SHOW_SECRET_PHRASE = 'SETTINGS_SHOW_SECRET_PHRASE',

  LOOKING_FOR_DEVICES = 'LOOKING_FOR_DEVICES',

  CONNECT_TO_LEDGER = 'CONNECT_TO_LEDGER',

  USER_PROFILE = 'USER_PROFILE',

  MNEMONIC_INPUT = 'MNEMONIC_INPUT',

  SELECT_DTAG = 'SELECT_DTAG',

  CHECK_MNEMONIC = 'CHECK_MNEMONIC',

  WELCOME_PAGE = 'WELCOME_PAGE',

  FULLSCREEN_STATUS_SCREEN = 'FULLSCREEN_STATUS_SCREEN',

  CONSENT_AGREEMENT = 'CONSENT_AGREEMENT',

  SEND_TIPS = 'SEND_TIPS',

  REPORT_POST = 'REPORT_POST',

  BOTTOM_MODAL = 'BOTTOM_MODAL',

  DEV_SCREEN = 'DEV_SCREEN',

  BROADCAST_TX = 'BROADCAST_TX',

  NO_DTAG_FOUND = 'NO_DTAG_FOUND',

  CREATE_DESMOS_PROFILE = 'CREATE_DESMOS_PROFILE',

  CONFIRM_ADDRESS = 'CONFIRM_ADDRESS',

  SELECT_CHAIN = 'SELECT_CHAIN',

  WELCOME_BACK = 'WELCOME_BACK',

  SELECT_LEDGER_APP = 'SELECT_LEDGER_APP',

  CONNECT_ADDRESS_GENERAL = 'CONNECT_ADDRESS_GENERAL',

  CONNECT_ADDRESS_ADVANCED = 'CONNECT_ADDRESS_ADVANCED',

  CONNECT_CHAIN_METHOD = 'CONNECT_CHAIN_METHOD',

  DISCONNECT_CHAIN_MODAL = 'DISCONNECT_CHAIN_MODAL',

  DISCONNECT_APP_MODAL = 'DISCONNECT_APP_MODAL',

  CONNECT_CHAIN_TX_DETAIL = 'CONNECT_CHAIN_TX_DETAIL',

  ACTION_AUTHORIZATION = 'ACTION_AUTHORIZATION',

  ENTER_COMMENT = 'ENTER_COMMENT',

  SELECT_POST_TYPE = 'SELECT_POST_TYPE',

  CREATE_TEXT_POST = 'CREATE_TEXT_POST',

  PROFILE_NFTS = 'PROFILE_NFTS',

  NFT_DETAILS = 'NFT_DETAILS',

  EDIT_PROFILE = 'EDIT_PROFILE',

  // Root navigation end

  // Authorize wallet stack start
  AUTHORIZE_WALLET = 'AUTHORIZE_WALLET',

  AUTH_LOOKING_FOR_DEVICES = 'AUTH_LOOKING_FOR_DEVICES',

  AUTH_CONNECT_TO_LEDGER = 'AUTH_CONNECT_TO_LEDGER',

  AUTH_UNLOCK_LOCAL_WALLET = 'AUTH_UNLOCK_LOCAL_WALLET',
  // Authorize wallet stack end

  // Post details start
  POST_DETAILS = 'POST_DETAILS',
  COMMENT_REPLIES = 'COMMENT_REPLIES',
  // Post details end

  // Post Interaction start
  POST_INTERACTION = 'POST_INTERACTION',
  POST_REACTIONS = 'POST_REACTIONS',
  POST_TIPS = 'POST_TIPS',
  // Post interaction end

  FOLLOWING_AND_FOLLOWERS = 'FOLLOWING_AND_FOLLOWERS',
  FOLLOWING = 'FOLLOWING',
  FOLLOWERS = 'FOLLOWERS',

  // Profile posts start
  PROFILE_POSTS = 'PROFILE_POSTS',
  PROFILE_POSTS_POSTS = 'PROFILE_POSTS_POSTS',
  PROFILE_POSTS_LIKED = 'PROFILE_POSTS_LIKED',
  PROFILE_POSTS_TIPPED = 'PROFILE_POSTS_TIPPED',
  // Profile posts end

  ADD_PROFILE = 'ADD_PROFILE',
  ADD_PROFILE_SELECT_ADDRESS_GENERAL = 'ADD_PROFILE_SELECT_ADDRESS_GENERAL',
  ADD_PROFILE_SELECT_ADDRESS_ADVANCED = 'ADD_PROFILE_SELECT_ADDRESS_ADVANCED',
  ADD_PROFILE_MODAL = 'ADD_PROFILE_MODAL',

  // Twitter connection start
  CONNECT_APP = 'CONNECT_APP',
  SELECT_TWEET = 'SELECT_TWEET',
  // Twitter connection end

  // Grants start
  GRANTS = 'GRANTS',
  GRANTS_DETAILS = 'GRANTS_DETAILS',
  // Grants end

  // Activities
  ACTIVITIES = 'ACTIVITIES',

  // Biometrics
  MANAGE_BIOMETRICS = 'MANAGE_BIOMETRICS',

  // Invites
  INVITES = 'INVITES',
}

export default ROUTES;
