enum ROUTES {
  LANDING = 'LANDING',

  MANAGE_CONNECTED_CHAINS = 'MANAGE_CONNECTED_CHAINS',

  HOME = 'HOME',

  ENTER_PASSWORD = 'ENTER_PASSWORD',

  PASSWORD_MANIPULATION = 'PASSWORD_MANIPULATION',

  RESULT_MODAL = 'RESULT_MODAL',

  CONFIRM_MODAL = 'CONFIRM_MODAL',

  SETTINGS = 'SETTINGS',

  SETTINGS_PROFILES = 'SETTINGS_PROFILES',

  SETTINGS_COMMUNITY = 'SETTINGS_COMMUNITY',

  SETTINGS_REVEAL_SECRET_PHRASE = 'SETTINGS_REVEAL_SECRET_PHRASE',

  SETTINGS_SHOW_SECRET_PHRASE = 'SETTINGS_SHOW_SECRET_PHRASE',

  LOOKING_FOR_DEVICES = 'LOOKING_FOR_DEVICES',

  CONNECT_TO_LEDGER = 'CONNECT_TO_LEDGER',

  USER_PROFILE = 'USER_PROFILE',

  MNEMONIC_INPUT = 'MNEMONIC_INPUT',

  CONSENT_AGREEMENT = 'CONSENT_AGREEMENT',
}

export default ROUTES;
