name: "Lint PR"
# Lint PR runs the proper PR linting
# This workflow is run on every pull request
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
