name: "Lint PR"
# Lint runs the linter over the entire repository.
# This workflow is run on every pull request and push to main.
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint-pr:
    if: startsWith(github.head_ref, 'l10n') == false && startsWith(github.head_ref, 'i10n') == false
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
      - name: Run lint ✅
        uses: amannn/action-semantic-pull-request@v4.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
